version: 2
jobs:
  build-hub:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/apps/hub
    steps:
      - checkout
      - run: npm install
  deploy-hub:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: git subtree push --prefix apps/hub https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  build-api:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/apps/knowledge
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build  -v ./...
      - run: go test -v ./...
  deploy-api:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: git subtree push --prefix apps/knowledge https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_API_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-hub
      - build-api
      - deploy-hub:
          filters:
            branches:
              only: master
          requires:
            - build-hub
      - deploy-api:
          filters:
            branches:
              only: master
          requires:
            - build-api

